#!/bin/bash
#BIOS mode

read -rp 'loading uk kb layout...'
loadkeys uk

read -rp 'enabling time and date...'
timedatectl set-ntp true

#eg sda1
read -rp 'enter disk to install arch on: ' DISK

fdisk "/dev/$DISK"

#eg 1
read -rp 'enter the swap partition number: ' SWAP_NO
read -rp 'enter the filesystem partition number: ' FS_NO

read -rp 'making filesystem...'
mkfs.ext4 "/dev/$DISK$FS_NO"

read -rp 'making swap partition...'
mkswap "/dev/$DISK$SWAP_NO"
swapon "/dev/$DISK$SWAP_NO"

read -rp 'mounting fs...'
mount "/dev/$DISK$FS_NO" /mnt

read -rp 'installing arch...'
pacstrap /mnt base linux linux-firmware wpa_supplicant netctl dhcpcd vim grub git vi sudo

read -rp 'generating fstab file...'
genfstab -U /mnt >> /mnt/etc/fstab

read -rp 'changing root to /mnt...'
arch-chroot /mnt


