#!/bin/bash
#BIOS mode

read -rp 'loading uk kb layout...'
loadkeys uk

read -rp 'enabling time and date...'
timedatectl set-ntp true

#eg sda
read -rp 'enter disk to install arch on: ' DISK

fdisk "/dev/$DISK"

#eg 1
read -rp 'enter the swap partition number: ' SWAP_NO
read -rp 'enter the filesystem partition number: ' FS_NO
#read -rp 'enter the efi partition number: ' EFI_NO

read -rp 'making filesystem...'
mkfs.ext4 "/dev/$DISK$FS_NO"

read -rp 'making swap partition...'
mkswap "/dev/$DISK$SWAP_NO"
swapon "/dev/$DISK$SWAP_NO"

read -rp 'mounting fs...'
mount "/dev/$DISK$FS_NO" /mnt
#mkdir /mnt/efi
#mount "/dev/$DISK$EFI_NO" /mnt/efi

read -rp 'installing arch...'
pacstrap /mnt base linux linux-firmware wpa_supplicant netctl dhcpcd vim grub efibootmgr git vi sudo dialog

read -rp 'generating fstab file...'
genfstab -U /mnt >> /mnt/etc/fstab

read -rp 'moving post-chroot script to /mnt...'
mv post-chroot /mnt

read -rp 'changing root to /mnt...'
arch-chroot /mnt
