#!/bin/sh
#BIOS mode

loadkeys uk

timedatectl set-ntp true

#eg sda1
read -p 'enter disk to install arch on: ' DISK

fdisk "/dev/$DISK"

#eg 1
read -p 'enter the swap partition number: ' SWAP_NO
read -p 'enter the filesystem partition number: ' FS_NO

mkfs.ext4 "/dev/$DISK$FS_NO"

mkswap "/dev/$DISK$SWAP_NO"
swapon "/dev/$DISK$SWAP_NO"

mount "/dev/$DISK$FS_NO" /mnt

pacstrap /mnt base linux linux-firmware wpa_supplicant netctl dhcpcd vim grub

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt

ln -sf /usr/share/zoneinfo/GMT /etc/localtime

hwclock --systohc

vim /etc/local.gen

locale-gen

echo "LANG=en_GB.UTF-8" > /etc/locale.conf

echo "KEYMAP=uk" > /etc/vconsole.conf

read -p 'enter the hostname for this new OS: ' HOSTNAME

echo "$HOSTNAME" > /etc/hostname

echo "127.0.0.1\tlocalhost" > /etc/hosts
echo "::1\t\t\tlocalhost" >> /etc/hosts
echo "127.0.1.1\t$HOSTNAME.localdomain $HOSTNAME"

passwd

grub-install --target=i386-pc /dev/$DISK

grub-mkconfig -o /boot/grub/grub.cfg

