#!/bin/bash

read -rp 'linking zoneinfo and localtime...'
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

read -rp 'setting clock...'
hwclock --systohc

read -rp 'uncomment your locale...'
vim /etc/locale.gen

read -rp 'running locale-gen...'
locale-gen

read -rp 'setting language...'
echo "LANG=en_GB.UTF-8" > /etc/locale.conf

read -rp 'setting keymap...'
echo "KEYMAP=uk" > /etc/vconsole.conf

read -rp 'enter the hostname for this new OS: ' HOSTNAME

echo "$HOSTNAME" > /etc/hostname

read -rp 'populating hosts file...'
printf "127.0.0.1\tlocalhost\n" > /etc/hosts
printf "::1\t\tlocalhost\n" >> /etc/hosts
printf "127.0.1.1\t%s.localdomain %s\n" "$HOSTNAME" "$HOSTNAME" >> /etc/hosts

echo 'enter root password'
passwd

read -rp 'enter disk: ' DISK
read -rp 'installing grub...'
grub-install --target=i386-pc "/dev/$DISK"
#uefi:
#reap -rp 'enter efi partition number: ' EFI
#mkdir efi
#mount "/dev/$DISK$EFI" efi
#grub-install --target=x86_64-efi --efi-directory=efi --bootloader-id=GRUB

read -rp 'generating grub config...'
grub-mkconfig -o /boot/grub/grub.cfg

